### ISSUE TITLE
Not working in 1.9

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#30]
Spigot `CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)`

The plugin loads, but doesn't function. And the command `/ne` is registered, but nothing happens when I type it.

```
[18:26:13] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.0
[18:26:13] [Server thread/ERROR]: Error occurred while enabling NametagEdit v4.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.loadPlayers(FlatFileConfig.java:117) ~[?:?]
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.load(FlatFileConfig.java:42) ~[?:?]
    at com.nametagedit.plugin.NametagHandler.<init>(NametagHandler.java:46) ~[?:?]
    at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:27) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

**Comment by comfysquirrel** [comment]
Oops never mind, I found the dev build of 4.0.2, that works on 1.9.
